import { cookies } from "next/headers";
import { createClient } from "@/lib/supabase/server";
import type { ChildProfileRow, UserRow, WorksheetLogRow } from "@/lib/db/types";

/**
 * Returns the public.users row for the current auth user.
 * The row is normally inserted by the auth trigger; null indicates a
 * fresh account whose trigger hasn't fired yet.
 */
export const getCurrentUserRow = async (): Promise<UserRow | null> => {
  const supabase = await createClient();
  const { data, error } = await supabase.from("users").select("*").maybeSingle();
  if (error) {
    console.warn("getCurrentUserRow:", error.message);
    return null;
  }
  return (data ?? null) as UserRow | null;
};

/**
 * Returns the first child profile (oldest), regardless of active selection.
 * Used for the "does any child exist?" gate that drives onboarding redirects.
 */
export const getChildProfile = async (): Promise<ChildProfileRow | null> => {
  const supabase = await createClient();
  const { data, error } = await supabase
    .from("children_profiles")
    .select("*")
    .order("created_at", { ascending: true })
    .limit(1)
    .maybeSingle();
  if (error) {
    console.warn("getChildProfile:", error.message);
    return null;
  }
  return (data ?? null) as ChildProfileRow | null;
};

/** All child profiles for the current user, oldest first. */
export const listChildProfiles = async (): Promise<ChildProfileRow[]> => {
  const supabase = await createClient();
  const { data, error } = await supabase
    .from("children_profiles")
    .select("*")
    .order("created_at", { ascending: true });
  if (error) {
    console.warn("listChildProfiles:", error.message);
    return [];
  }
  return (data ?? []) as ChildProfileRow[];
};

/**
 * Fetch a specific child by id. RLS already scopes to the current user, so
 * a non-owned id simply returns null.
 */
export const getChildProfileById = async (
  id: string,
): Promise<ChildProfileRow | null> => {
  const supabase = await createClient();
  const { data, error } = await supabase
    .from("children_profiles")
    .select("*")
    .eq("id", id)
    .maybeSingle();
  if (error) {
    console.warn("getChildProfileById:", error.message);
    return null;
  }
  return (data ?? null) as ChildProfileRow | null;
};

export const countChildProfiles = async (): Promise<number> => {
  const supabase = await createClient();
  const { count, error } = await supabase
    .from("children_profiles")
    .select("id", { count: "exact", head: true });
  if (error) {
    console.warn("countChildProfiles:", error.message);
    return 0;
  }
  return count ?? 0;
};

export const ACTIVE_CHILD_COOKIE = "lernikon_active_child";

/**
 * Resolve the "active" child for the current user. Priority:
 *   1. explicit selection in the `lernikon_active_child` cookie
 *   2. child that owns the most recent row in worksheets_log
 *   3. oldest child by created_at
 * Returns null only if the user has no children at all.
 */
export const getActiveChildProfile = async (
  userId: string,
): Promise<ChildProfileRow | null> => {
  const children = await listChildProfiles();
  if (children.length === 0) return null;

  const cookieStore = await cookies(),
    cookieId = cookieStore.get(ACTIVE_CHILD_COOKIE)?.value,
    fromCookie = cookieId
      ? children.find((c) => c.id === cookieId) ?? null
      : null;
  if (fromCookie) return fromCookie;

  const supabase = await createClient(),
    { data: lastLog } = await supabase
      .from("worksheets_log")
      .select("child_id")
      .eq("user_id", userId)
      .not("child_id", "is", null)
      .order("generated_at", { ascending: false })
      .limit(1)
      .maybeSingle();

  if (lastLog?.child_id) {
    const fromLog = children.find((c) => c.id === lastLog.child_id);
    if (fromLog) return fromLog;
  }

  return children[0];
};

/** Last N worksheets generated by the current user, newest first. */
export const listRecentWorksheets = async (
  userId: string,
  limit = 5,
): Promise<WorksheetLogRow[]> => {
  const supabase = await createClient();
  const { data, error } = await supabase
    .from("worksheets_log")
    .select("*")
    .eq("user_id", userId)
    .order("generated_at", { ascending: false })
    .limit(limit);
  if (error) {
    console.warn("listRecentWorksheets:", error.message);
    return [];
  }
  return (data ?? []) as WorksheetLogRow[];
};

export const countWorksheetsLast24h = async (userId: string): Promise<number> => {
  const supabase = await createClient(),
    since = new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString();
  const { count, error } = await supabase
    .from("worksheets_log")
    .select("id", { count: "exact", head: true })
    .eq("user_id", userId)
    .gte("generated_at", since);
  if (error) {
    console.warn("countWorksheetsLast24h:", error.message);
    return 0;
  }
  return count ?? 0;
};
